config/routes.rb
ENV["MAGENT_WEB_PATH"] = "/magent"
require 'magent_web'

#ENV["BUGHUNTER_PATH"] = "/errors"
#require 'bug_hunter'

Rails.application.routes.draw do
  devise_for(:users,
             :path_names => {:sign_in => 'login', :sign_out => 'logout'},
             :controllers => {:registrations => 'users', :omniauth_callbacks => "multiauth/sessions"}) do
  end
  match '/groups/:group_id/check_custom_domain' => 'groups#check_custom_domain',
  :as => 'check_custom_domain'
  match '/groups/:group_id/reset_custom_domain' => 'groups#reset_custom_domain',
   :method => :post, :as => 'reset_custom_domain'
  match '/connect' => 'users#social_connect', :method => :get, :as => :social_connect
  match '/invitations/accept' => 'invitations#accept', :method => :get, :as => :accept_invitation
  match '/disconnect_twitter_group' => 'groups#disconnect_twitter_group', :method => :get
  match '/group_twitter_request_token' => 'groups#group_twitter_request_token', :method => :get
  match 'confirm_age_welcome' => 'welcome#confirm_age', :as => :confirm_age_welcome
  match '/change_language_filter' => 'welcome#change_language_filter', :as => :change_language_filter
  match '/register' => 'users#create', :as => :register
  match '/signup' => 'users#new', :as => :signup
  match '/plans' => 'doc#plans', :as => :plans
  match '/chat' => 'doc#chat', :as => :chat
  match '/shapado_feedback' => 'welcome#feedback', :as => :feedback
  match '/feedback' => 'welcome#fake_feedback'
  match '/send_feedback' => 'welcome#send_shapado_feedback', :as => :send_feedback
  match '/send_shapado_feedback' => 'welcome#send_feedback', :as => :send_feedback
  match '/settings' => 'users#edit', :as => :settings
  match '/tos' => 'doc#tos', :as => :tos
  match '/privacy' => 'doc#privacy', :as => :privacy
  match '/widgets/embedded/:id' => 'widgets#embedded', :as => :embedded_widget
  match '/suggestions' => 'users#suggestions', :as => :suggestions
  match '/activities' => 'activities#index', :as => :activities
  match '/activities/:id' => 'activities#show', :as => :activity, :method => :get

  match '/update_stripe' => 'invoices#webhook', :method => :post

  get "mobile/index"

  match '/users/auth/:provider' => 'users#auth', :as => :auth_users

  match '/facebook' => "facebook#index", :as => :facebook, :method => :any
  match '/facebook/enable_page' => 'facebook#enable_page', :as => :enable_page_facebook

  mount MagentWeb.app => ENV["MAGENT_WEB_PATH"]
#  mount BugHunter.app => ENV["BUGHUNTER_PATH"]

  match '/facts' => redirect("/")
  match '/users/:id/:slug' => redirect("/users/%{slug}"), :as => :user_se_url, :id => /\d+/
  resources :users do
    collection do
      get :autocomplete_for_user_login
      post :connect
      get :follow_tags
      get :unfollow_tags
      get :leave
      get :join
      post :connect
      get :new_password
    end

    member do
      get :feed
      get :expertise
      get :preferred
      get :by_me
      get :contributed
      post :unfollow
      post :follow
      get :answers
      get :follows
      get :activity
    end
  end

  resources :badges

  resources :searches, :path => "search", :as => "search"

  resources :pages do
    member do
      get :js
      get :css
    end
  end

  resources :announcements do
    collection do
      get :hide
    end
  end

  resources :imports do
    collection do
      post :send_confirmation
    end
  end

  get '/questions/:id/:slug' => 'questions#show', :as => :se_url, :id => /\d+/
  post '/questions/:id/start_reward' => "reward#start", :as => :start_reward
  get '/questions/:id/close_reward' => "reward#close", :as => :close_reward

  match '/answers(.format)' => 'answers#index', :as => :answers

  scope('questions') do
    resources :tags, :constraints => { :id => /\S+/ }
  end

  match 'questions/unanswered' => redirect("/questions?unanswered=1")

  resources :questions do
    resources :votes
    resources :flags
    collection do
      get :tags_for_autocomplete
      get :related_questions
      get :random

      match '/:filter' => 'questions#index', :as => :filtered, :constraints => { :filter => /all|unanswered|by_me|feed|preferred|contributed|expertise/ }
    end

    member do
      get :solve
      get :unsolve
      get :flag
      get :follow
      get :unfollow
      get :history
      get :revert
      get :diff
      get :move
      put :move_to
      get :retag
      put :retag_to
      get :remove_attachment
      get :twitter_share
    end

    resources :comments do
      resources :votes
    end

    resources :answers do
      resources :votes
      resources :flags
      member do
        get :favorite
        get :unfavorite
        get :flag
        get :history
        get :diff
        get :revert
      end

      resources :comments do
        resources :votes
      end
    end

    resources :close_requests
    resources :open_requests
  end

  match 'questions/tags/:tags' => 'tags#show', :as => :question_tag
  match 'questions/tagged/:tags' => redirect { |env, req| "/questions/tags/#{req.params[:tags].gsub(' ', '+')}" }, :tags => /.+/ #support se url

  resources :groups do
    collection do
      get :autocomplete_for_group_slug
      get :add_to_facebook
      post :join
    end

    member do
      get :allow_custom_ads
      get :disallow_custom_ads
      post :close
      post :update_card
      get :accept

      post :upgrade
      post :downgrade
      post :set_columns
    end
  end

  resources :invitations do
    member do
      post :revoke
      post :resend
    end
  end

  resources :invoices do
    member do
      get :success
    end
    collection do
      get :auto_update
      get :upcoming
    end
  end

  scope '/manage' do
    resources :widgets do
      member do
        post :move
      end
    end

    resources :themes do
      member do
        get :remove_bg_image
        put :apply
        get :ready
        get :download
      end

      collection do
        post :import
      end
    end
    resources :constrains_configs
    resources :members
  end

  scope '/manage', :as => 'manage' do
    controller 'admin/manage' do
      match 'edit_card' => :edit_card
      match 'social' => :social
      match 'properties' => :properties
      match 'theme' => :theme
      match 'actions' => :actions
      match 'stats' => :stats
      match 'reputation' => :reputation
      match 'content' => :content
      match 'invitations' => :invitations
      match 'appearance' => :appearance
      match 'access' => :access
      match 'close_group' => :close_group
    end
  end
  match '/manage/properties/:tab' => 'admin/manage#properties', :as => :manage_properties_tab

  namespace :moderate do
    resources :questions do
      collection do
        get :flagged
        get :to_close
        get :to_open
        post :manage
      end
      member do
        get :banning
        put :ban

        get :closing
        put :close
        get :opening
        put :open
      end
    end
    resources :answers do
      collection do
        post :manage
      end
      member do
        get :banning
        put :ban
      end
    end
    resources :users
  end

  match '/moderate' => 'moderate/questions#index'
#   match '/search' => 'searches#index', :as => :search
  match '/about' => 'groups#show', :as => :about
  root :to => 'questions#index'
  #match '/:controller(/:action(/:id))'
  match '*a', :to => 'public_errors#routing'
end

app/helpers/groups_helper.rb
module GroupsHelper
  def group_logo_img(group, options)
    options[:alt] ||= group.name
    options[:title] ||= group.name

    begin
      if group.has_logo?
        if options[:size].nil?
#           options.merge!(:width => group.logo_info["width"], :height => group.logo_info["height"])
        end
        image_tag(logo_path(current_group), options)
      else
        image_tag("shapado-brand.png", options)
      end
    rescue Exception => e
      Rails.logger.info e.backtrace.join("\n\t")
      image_tag("shapado-brand.png", options)
    end
  end
end

app/views/groups/_form.html.haml
.field
  = form.label :name, t('name', :scope => "activerecord.attributes.group"), :class => "label"
  = form.text_field :name, :class => "text_field"

-if @group.new? || !@group.shapado_version.has_custom_domain?
  .field
    = form.label :subdomain, "URL", :class => "label"
    .domain
      %small
        ="#{request.protocol}"
      = form.text_field :subdomain, :class=>"text_field"
      %small
        = ".#{request.domain}"

-if current_user.admin?
  .field
    = form.label :domain,  t('domain', :scope => "activerecord.attributes.group"), :class => "label"
    .domain
      %small
        =request.protocol
      = form.text_field :domain, :class=> "text_field"

  .field
    = form.label :description,  t('description', :scope => "activerecord.attributes.group"), :class => "label"
    -if current_group.wysiwyg_editor
      = form.text_area :description, :class => "text_area wysiwyg_editor", :value => markdown(@group.description)
    -else
      = form.text_area :description, :class => "text_area markdown_editor"
      %small
        = t('.description_legend')
      %label.label
        = t("global.preview")
      .markdown_preview.markdown
        =markdown(@group.description)

-if true
  .field
    .checkbox
      = form.label :isolate, t(".isolate_group"), :class => "radio"
      = form.check_box :isolate, :class => "checkbox"
  .field
    .checkbox
      = form.label :private, t(".custom_analytics"), :class => "radio"
      = form.check_box :has_custom_analytics, :class => "checkbox"
      %small{:style => "margin-bottom: 20px;"}
        = t(".analytics_legend")

.field{style: "clear: both"}
  =form.label :layout, t('layout', :scope => "activerecord.attributes.group"), :class => "label"
  =form.select :layout, [['Default', 'application'], ['2-Columns', 'classic']]

-if !@group.new?
  - if @group.has_custom_analytics
    .field
      = form.label :analytics_engine, t(".analytics_engine"), :class => "label"
      =  select("group", "analytics_vendor", [['Google Analytics', 'googlean']])

    .field
      = form.label :analytics_id, t(".website_analytics_id"), :class => "label"
      = form.text_field :analytics_id, :class=> "text_field"

  .field
    .checkbox
      = form.label :wysiwyg_editor, t('wysiwyg_editor', :scope => "activerecord.attributes.group"), :class => "radio"
      = form.check_box :wysiwyg_editor, :class => "checkbox"

  .field
    .checkbox
      = form.label :enable_latex, t('enable_latex', :scope => "activerecord.attributes.group"), :class => "radio"
      = form.check_box :enable_latex, :class => "checkbox"

  .field
    .checkbox
      = form.label :enable_mathjax, t('enable_mathjax', :scope => "activerecord.attributes.group"), :class => "radio"
      = form.check_box :enable_mathjax, :class => "checkbox"
  .field
    .checkbox
      = form.label :fb_button, t('fb_button', :scope => "activerecord.attributes.group"), :class => "radio"
      = form.check_box :fb_button, :class => "checkbox"
  .field
    .checkbox
      = form.label :track_users, t('track_users', :scope => "activerecord.attributes.group"), :class => "radio"
      = form.check_box :track_users, :class => "checkbox"

  .field
    = form.label :legend, t('legend', :scope => "activerecord.attributes.group"), :class => "label"
    = form.text_field :legend, :class => "text_field"
    %small
      = t('.legend_legend')

.field
  = form.label :default_tags, t('default_tags', :scope => "activerecord.attributes.group"), :class => "label"
  = form.text_field :default_tags, :value => @group.default_tags.join(", "), :class => "text_field"
  %small
    = t('.default_tags_legend')

-if AppConfig.enable_i18n
  .field
    = form.label :language, t(:language, :scope => "activerecord.attributes.group"), :class => "label"
    = form.select :language, AVAILABLE_LANGUAGES.collect {|lang| [ language_desc(lang), lang ] }, :selected => @group.language || 'en', :class => "select"
  .field
    = form.label :language, t(:languages, :scope => "activerecord.attributes.group"), :class => "label"
    = form.select :languages, AVAILABLE_LANGUAGES.collect{|lang| [language_desc(lang), lang]}, {:selected => @group.languages.to_a},{:multiple => true}
-else
  = form.hidden_field :language, :value => (AppConfig.default_language || 'en')

app/views/groups/_group.html.haml
%li.clearfix
  .logo
    -if group.has_logo?
      = link_to image_tag(logo_path(group), :style => "height: 64px; width: 128px; vertical-align: top"), domain_url(:custom => group.domain)
    -else
      = image_tag("default_logo.png", :style => "height: 64px; width: 128px; vertical-align: top", :class => "group_logo")

  .summary
    %h3
      = link_to group.name, domain_url(:custom => group.domain)
    .markdown.group_description
      =raw auto_link(markdown(group.description))

  .actions
    = link_to t(".about"), group, :class => "button"
    -if logged_in?
      -if current_user.can_modify?(group) || current_user.owner_of?(group)
        = link_to t(".admin", :default => :"shared.topbar.admin"), domain_url(:controller => "manage", :action => "properties", :custom => group.domain)
        -if group.state == "active"
          = link_to t(".close"), close_group_path(group), :class => "cancel"
      -if current_user.admin?
        = link_to t("scaffold.destroy"), group, :confirm => t('scaffold.are_you_sure'), :method => :delete
        - if group.shapado_version.has_custom_ads?
          = link_to t(".disallow_ads"), disallow_custom_ads_group_path(group)
        -else
          = link_to t(".allow_ads"), allow_custom_ads_group_path(group)

app/views/groups/_reputation_constrains_form.haml
-ConstrainsConfig::CONSTRAINS.each do |key, value|
  - value = @group.reputation_constrains[key]
  .field
    - name = "group[reputation_constrains[#{key}]]"
    = label_tag name, Group.humanize_reputation_constrain(key), :class => "label"
    = number_field_tag name, value, :class => "text_field"

app/views/groups/_reputation_rewards_form.haml
.field
  =reputation_rewards_form.label :daily_cap, t("activerecord.attributes.group.daily_cap"), :class => "label"
  =reputation_rewards_form.number_field :daily_cap, :class => "text_field"

-@group.reputation_rewards.sort.each do |key, value|
  .field
    -name = "group[reputation_rewards[#{key}]]"
    =label_tag name, Group.humanize_reputation_constrain(key), :class => "label"
    =number_field_tag name, value, :class => "text_field"

app/views/groups/_top_grouplist.html.haml
%li.group
  = link_to "Groups", "#"
  %ul.drop-menu
    -if logged_in?
      -cache_for("usergroups_#{current_user.id}_#{current_user.memberships.count}") do
        -current_user.groups.only(:name, :domain).limit(10).all.each do |group|
          %li
            = link_to group.name, domain_url(:custom => group.domain)
    -else
      -cache_for("usergroups_active") do
        -Group.only(:name, :domain).where(:state => "active", :private => false).order_by([:activity_rate, :desc]).limit(10).all.each do |group|
          %li
            = link_to group.name, domain_url(:custom => group.domain)
    %li
      = link_to t("groups.new.title"), new_group_path

app/views/groups/check_custom_domain.html.haml
%h2= t('users.check_custom_domain.title')
= form_for(:group, :url => reset_custom_domain_path(@group.id)) do |f|
  = f.submit t('users.check_custom_domain.reset_domain_button', :domain => "#{@group.slug}.#{AppConfig.domain}")
  = link_to t('users.check_custom_domain.refresh'), ""
  = link_to t('users.check_custom_domain.working_domain_link'), "#{domain_url(:custom => @group.domain)}/manage/properties/domain"
%iframe{:src=>"http://#{@group.domain}:#{request.port}", :style=>"width: 100%;height: 800px;"}

app/views/groups/edit.html.haml
%h1
  = t('.title')
%p.description

=form_for(@group, :html => {:class => "form", :multipart => true}) do |f|
  = f.error_messages
  = render :partial => "form", :object => f

  .buttons
    = link_to t("scaffold.back"), groups_path, :class => "cancel button"
    = link_to t("scaffold.show"), group_path(@group), :class => "button"
    = t("global.or")
    = f.submit t("scaffold.update"), :class => "save"
    = t("global.or")

app/views/groups/index.html.haml
.groups_container
  %h1
    = t('.title')
  %p.description
    - link = link_to t(".create_your_own"), new_group_path, :class => "request_group"
    =raw t('.description', :link => link)

  = form_tag groups_path, :id => "filter_groups", :method => "get" do
    .field
      = label_tag :q, t(".filter")
      = text_field_tag "q", params[:q]
      = submit_tag("filterr")

  %ul.items#groups
    = render :partial => "group", :collection => @groups

  #additional_info.clearfix
    = paginate @groups

app/views/groups/new.html.haml
%h1
  = t(".title")
%p.description

= form_for(@group, :html => {:class => "form", :multipart => true}) do |f|
  = f.error_messages
  = render :partial => "form", :object => f

  .buttons
    = f.submit  t("scaffold.create"), :class => "save"
    = t("global.or")
    = link_to  t("scaffold.back"), groups_path, :class => "cancel button"

app/views/groups/show.html.haml
-content_for :subtabs do
  .navtitle
    = t(".title", :name => h(@group.name))

#show_group
  -if @group.has_logo?
    = image_tag(logo_path(@group), :class => "group_logo")

  .markdown
    =raw find_and_preserve(shapado_auto_link(markdown(@group.description)))
  .clear
  -if !@group.isolate && @group.owner.display_name
    %b= t("activerecord.attributes.group.group_created_by")
    = link_to @group.owner.display_name, user_path(@group.owner)

  -case @group.state
    -when "pending"
      .message.warn
        .internal
          = t(".group_awaiting_acceptance")
    -when "close"
      .message.warn
        .internal
          = t(".group_closed")

  .actions
    -if !@group.isolate
      = link_to t(".visit_group"), domain_url(:custom => @group.domain)
    -if logged_in?
      -if current_user.owner_of?(@group)
        = link_to t(".admin", :default => :"shared.topbar.admin"), domain_url(:controller => "manage", :action => "properties", :custom => @group.domain)
      -if current_user.admin? && @group.state == "pending"
        = link_to t(".accept_group"), accept_group_path(@group)
        = link_to t(".accept_group_with_custom_ads"), accept_group_path(@group, :has_custom_ads => true)
      -if current_user.can_modify?(@group) && @group.state == "active"
        = link_to t(".close_group"), close_group_path(@group)

app/views/groups/upgrade.html.haml
=payment_form "A Title"