config/routes.rb
ENV["MAGENT_WEB_PATH"] = "/magent"
require 'magent_web'

#ENV["BUGHUNTER_PATH"] = "/errors"
#require 'bug_hunter'

Rails.application.routes.draw do
  devise_for(:users,
             :path_names => {:sign_in => 'login', :sign_out => 'logout'},
             :controllers => {:registrations => 'users', :omniauth_callbacks => "multiauth/sessions"}) do
  end
  match '/groups/:group_id/check_custom_domain' => 'groups#check_custom_domain',
  :as => 'check_custom_domain'
  match '/groups/:group_id/reset_custom_domain' => 'groups#reset_custom_domain',
   :method => :post, :as => 'reset_custom_domain'
  match '/connect' => 'users#social_connect', :method => :get, :as => :social_connect
  match '/invitations/accept' => 'invitations#accept', :method => :get, :as => :accept_invitation
  match '/disconnect_twitter_group' => 'groups#disconnect_twitter_group', :method => :get
  match '/group_twitter_request_token' => 'groups#group_twitter_request_token', :method => :get
  match 'confirm_age_welcome' => 'welcome#confirm_age', :as => :confirm_age_welcome
  match '/change_language_filter' => 'welcome#change_language_filter', :as => :change_language_filter
  match '/register' => 'users#create', :as => :register
  match '/signup' => 'users#new', :as => :signup
  match '/plans' => 'doc#plans', :as => :plans
  match '/chat' => 'doc#chat', :as => :chat
  match '/shapado_feedback' => 'welcome#feedback', :as => :feedback
  match '/feedback' => 'welcome#fake_feedback'
  match '/send_feedback' => 'welcome#send_shapado_feedback', :as => :send_feedback
  match '/send_shapado_feedback' => 'welcome#send_feedback', :as => :send_feedback
  match '/settings' => 'users#edit', :as => :settings
  match '/tos' => 'doc#tos', :as => :tos
  match '/privacy' => 'doc#privacy', :as => :privacy
  match '/widgets/embedded/:id' => 'widgets#embedded', :as => :embedded_widget
  match '/suggestions' => 'users#suggestions', :as => :suggestions
  match '/activities' => 'activities#index', :as => :activities
  match '/activities/:id' => 'activities#show', :as => :activity, :method => :get

  match '/update_stripe' => 'invoices#webhook', :method => :post

  get "mobile/index"

  match '/users/auth/:provider' => 'users#auth', :as => :auth_users

  match '/facebook' => "facebook#index", :as => :facebook, :method => :any
  match '/facebook/enable_page' => 'facebook#enable_page', :as => :enable_page_facebook

  mount MagentWeb.app => ENV["MAGENT_WEB_PATH"]
#  mount BugHunter.app => ENV["BUGHUNTER_PATH"]

  match '/facts' => redirect("/")
  match '/users/:id/:slug' => redirect("/users/%{slug}"), :as => :user_se_url, :id => /\d+/
  resources :users do
    collection do
      get :autocomplete_for_user_login
      post :connect
      get :follow_tags
      get :unfollow_tags
      get :leave
      get :join
      post :connect
      get :new_password
    end

    member do
      get :feed
      get :expertise
      get :preferred
      get :by_me
      get :contributed
      post :unfollow
      post :follow
      get :answers
      get :follows
      get :activity
    end
  end

  resources :badges

  resources :searches, :path => "search", :as => "search"

  resources :pages do
    member do
      get :js
      get :css
    end
  end

  resources :announcements do
    collection do
      get :hide
    end
  end

  resources :imports do
    collection do
      post :send_confirmation
    end
  end

  get '/questions/:id/:slug' => 'questions#show', :as => :se_url, :id => /\d+/
  post '/questions/:id/start_reward' => "reward#start", :as => :start_reward
  get '/questions/:id/close_reward' => "reward#close", :as => :close_reward

  match '/answers(.format)' => 'answers#index', :as => :answers

  scope('questions') do
    resources :tags, :constraints => { :id => /\S+/ }
  end

  match 'questions/unanswered' => redirect("/questions?unanswered=1")

  resources :questions do
    resources :votes
    resources :flags
    collection do
      get :tags_for_autocomplete
      get :related_questions
      get :random

      match '/:filter' => 'questions#index', :as => :filtered, :constraints => { :filter => /all|unanswered|by_me|feed|preferred|contributed|expertise/ }
    end

    member do
      get :solve
      get :unsolve
      get :flag
      get :follow
      get :unfollow
      get :history
      get :revert
      get :diff
      get :move
      put :move_to
      get :retag
      put :retag_to
      get :remove_attachment
      get :twitter_share
    end

    resources :comments do
      resources :votes
    end

    resources :answers do
      resources :votes
      resources :flags
      member do
        get :favorite
        get :unfavorite
        get :flag
        get :history
        get :diff
        get :revert
      end

      resources :comments do
        resources :votes
      end
    end

    resources :close_requests
    resources :open_requests
  end

  match 'questions/tags/:tags' => 'tags#show', :as => :question_tag
  match 'questions/tagged/:tags' => redirect { |env, req| "/questions/tags/#{req.params[:tags].gsub(' ', '+')}" }, :tags => /.+/ #support se url

  resources :groups do
    collection do
      get :autocomplete_for_group_slug
      get :add_to_facebook
      post :join
    end

    member do
      get :allow_custom_ads
      get :disallow_custom_ads
      post :close
      post :update_card
      get :accept

      post :upgrade
      post :downgrade
      post :set_columns
    end
  end

  resources :invitations do
    member do
      post :revoke
      post :resend
    end
  end

  resources :invoices do
    member do
      get :success
    end
    collection do
      get :auto_update
      get :upcoming
    end
  end

  scope '/manage' do
    resources :widgets do
      member do
        post :move
      end
    end

    resources :themes do
      member do
        get :remove_bg_image
        put :apply
        get :ready
        get :download
      end

      collection do
        post :import
      end
    end
    resources :constrains_configs
    resources :members
  end

  scope '/manage', :as => 'manage' do
    controller 'admin/manage' do
      match 'edit_card' => :edit_card
      match 'social' => :social
      match 'properties' => :properties
      match 'theme' => :theme
      match 'actions' => :actions
      match 'stats' => :stats
      match 'reputation' => :reputation
      match 'content' => :content
      match 'invitations' => :invitations
      match 'appearance' => :appearance
      match 'access' => :access
      match 'close_group' => :close_group
    end
  end
  match '/manage/properties/:tab' => 'admin/manage#properties', :as => :manage_properties_tab

  namespace :moderate do
    resources :questions do
      collection do
        get :flagged
        get :to_close
        get :to_open
        post :manage
      end
      member do
        get :banning
        put :ban

        get :closing
        put :close
        get :opening
        put :open
      end
    end
    resources :answers do
      collection do
        post :manage
      end
      member do
        get :banning
        put :ban
      end
    end
    resources :users
  end

  match '/moderate' => 'moderate/questions#index'
#   match '/search' => 'searches#index', :as => :search
  match '/about' => 'groups#show', :as => :about
  root :to => 'questions#index'
  #match '/:controller(/:action(/:id))'
  match '*a', :to => 'public_errors#routing'
end

app/helpers/layout_helper.rb
module LayoutHelper
  def tab_entry(element, text, path, options = {}, html_opts = {})
    options[:selected] ||= "selected"
    options[:link_opts] ||= {}

    if request.path == path
      if html_opts[:class]
        html_opts[:class] = "#{html_opts[:class]} #{options[:selected]}"
      else
        html_opts[:class] = options[:selected]
      end
    end

    if element != "a"
      content_tag(element, html_opts) do
        link_to(text, path, options[:link_opts])
      end
    else
      link_to text, path, html_opts.merge(options[:link_opts])
    end
  end

  def pjax_tab_entry(element, text, layout, path, options = {}, html_opts = {})
    link_opts = options[:link_opts] || {}
    if link_opts[:class].nil? || !(link_opts[:class] =~ /pjax/)

      link_opts[:class] = "#{link_opts[:class]} pjax"
    end

    link_opts.merge!(:"data-layout" => layout)
    options[:link_opts] = link_opts

    tab_entry(element, text, path, options, html_opts)
  end

  def pjax_link_to(text, layout, path, options = {})
    klass = "pjax"
    if extra_class = options.delete(:class) || options.delete('class')
      klass << " " << extra_class
    end

    link_to text, path, options.merge(:class => klass, :"data-layout" => layout)
  end

  def render_app_config
    content_tag(:span, "", {:id=>"appconfig",:"data-g"=>current_group.id})
  end

  def questions_link_for(action)
    case action
    when "by_me"
      {"controller" => "questions", "action" => "by_me"}
    when "feed"
      {"controller" => "questions", "action" => "feed"}
    when "preferred"
      {"controller" => "questions", "action" => "preferred"}
    when "expertise"
      {"controller" => "questions", "action" => "expertise"}
    when "contributed"
      {"controller" => "questions", "action" => "contributed"}
    else
      {"controller" => "questions", "action" => "index"}
    end
  end

  def ie_tag(name=:body, attrs={}, &block)
    attrs.symbolize_keys!
    haml_concat("<!--[if lt IE 7]> #{ tag(name, add_class('ie6', attrs), true) } <![endif]-->".html_safe)
    haml_concat("<!--[if IE 7]>    #{ tag(name, add_class('ie7', attrs), true) } <![endif]-->".html_safe)
    haml_concat("<!--[if IE 8]>    #{ tag(name, add_class('ie8', attrs), true) } <![endif]-->".html_safe)
    haml_concat("<!--[if gt IE 8]><!-->".html_safe)
    haml_tag name, attrs do
      haml_concat("<!--<![endif]-->".html_safe)
      block.call
    end
  end

  def ie_html(attrs={}, &block)
    ie_tag(:html, attrs, &block)
  end

  def ie_body(attrs={}, &block)
    ie_tag(:body, attrs, &block)
  end

private

  def add_class(name, attrs)
    classes = attrs[:class] || ''
    classes.strip!
    classes = ' ' + classes if !classes.blank?
    classes = name + classes
    attrs.merge(:class => classes)
  end
end

app/views/shared/layout/_activities.html.haml
-if @activities
  %h4
    = t(".title")

  %ul.list
    -@activities.each do |activity|
      = render :partial => "users/activity_base", :locals => {:activity => activity}

app/views/shared/layout/_column1.html.haml
%section.left-panel#column1
  .widget-links.module
    %nav
      %ul
        = tab_entry "li", t('layouts.application.all'), questions_path, :selected => "active", :link_opts => {:"class" => "pjax", :"data-layout" => "index"}
        -if logged_in?
          = tab_entry "li", t('layouts.application.followed'), feed_user_path(current_user), :selected => "active", :link_opts => {:"class" => "pjax", :"data-layout" => "index"}
          = tab_entry "li", t('layouts.application.by_me'), by_me_user_path(current_user), :selected => "active", :link_opts => {:"class" => "pjax", :"data-layout" => "index"}
          = tab_entry "li", t('layouts.application.preferred'), preferred_user_path(current_user), :selected => "active", :link_opts => {:"class" => "pjax", :"data-layout" => "index"}
          = tab_entry "li", t('layouts.application.contributed'), contributed_user_path(current_user), :selected => "active", :link_opts => {:"class" => "pjax", :"data-layout" => "index"}
          = tab_entry "li", t('layouts.application.collaborate'), expertise_user_path(current_user), :selected => "active", :link_opts => {:"class" => "pjax", :"data-layout" => "index"}
          = tab_entry "li", t('layouts.application.search'), '/search', :selected => "active", :link_opts => {:"class" => "pjax", :"data-layout" => "index"}
        %li
          = link_to t('layouts.application.faq'), page_path('faq'), :class => "pjax", :"data-layout" => "index"

  -if user_signed_in? && current_user.searches.count > 0
    .widget-links.module
      %nav
        %ul
          -current_user.searches.each do |search|
            %li
              = tab_entry "li", search.name, search_path(search), :selected => "active", :link_opts => {:"class" => "pjax", :"data-layout" => "index", :rel => 'nofollow'}

  .widget-links.module
    %nav
      %ul
        %li
          = link_to t('layouts.application.random_question'), random_questions_path(:unanswered => true), :class => "pjax", :"data-layout" => "question", :rel => 'nofollow'


  = render "shared/widgets", :context => 'mainlist', :position => 'navbar'

app/views/shared/layout/_column2.html.haml
%section.content-panel#column2
  #main-content-wrap{:class => @active_tab}
    - if params[:controller] =~ /moderate\//
      = render "shared/moderate_navigation"
    = yield

app/views/shared/layout/_column3.html.haml
-if @show_sidebar
  %section.right-panel#column3
    = render "shared/widgets", :context => @widget_context, :position => 'sidebar'

    = yield :sidebar

app/views/shared/layout/_css.html.haml
= stylesheet_link_tag('application')

= yield :css
-current_theme = current_group.current_theme || Theme.where(:is_default => true).first
%link{:href => css_group_path(current_group, params[:test_theme] || current_theme.id, current_theme.version),  :rel => "stylesheet", :media => "screen", :type => "text/css"}

<!--[if lt IE 8]><link type="text/css" rel="stylesheet" media="screen" href="/stylesheets/ie7.css"><![endif]-->

app/views/shared/layout/_feed_urls.html.haml
%br
-if @feed_urls && !@feed_urls.empty?
  -@feed_urls.each do |title, url|
    %a.feed_url{:href => url}
      %span.icon
        =image_tag "atom.png"
      %span.text
        = h(title)
    .clear
    %br

app/views/shared/layout/_feeds.html.haml
-if @feed_urls && !@feed_urls.empty?
  -@feed_urls.each do |title, url|
    %link{:rel=>"alternate", :type=>"application/atom+xml", :title => h(title), :href=> url}

app/views/shared/layout/_footer.html.haml
#login_dialog.top-bar{'data-title' => t('devise.sessions.link')}
  %ul.auth-list
    %li
      = render "shared/login_drop_down"
#join_dialog.hide{'data-title' => t('layouts.application.join_group', :group => current_group.name)}
  = link_to t('layouts.application.not_member_join_dialog', :group => current_group.name), join_groups_path , :id => 'join_dialog_link'
%footer
  %nav
    %ul
      -if !current_group.footer.blank?
        = raw(current_group.footer)
      -else
        %li
          = link_to t('global.blog'), 'http://blog.ricodigo.com/blog/categories/shapado/'
        %li
          = link_to 'Twitter', 'http://twitter.com/shapado'
        %li
          = link_to 'Identi.ca', 'http://identi.ca/shapado'
        %li
          = link_to 'IRC', 'irc://irc.freenode.org/shapado'
        %li
          = link_to t('global.chat'), domain_url+'/chat'
        %li
          = link_to t('global.feedback'), feedback_url, :class => "feedback", :id => "feedback"
        %li
          = link_to t('global.tos'), tos_path
        %li
          = link_to t('global.privacy'), privacy_path
  %p
    - cc_link = link_to 'Creative Commons Attribution 3.0', 'http://creativecommons.org/licenses/by/3.0/'
    = raw t('.cc_footer', :cc_link => cc_link)
  %p
    / !!!!!!!!!!!! DO NOT REMOVE LINK TO SOURCE CODE AND LICENSE !!!!!!!!!!!!!
    - agpl_link = link_to 'GNU Affero General Public License','http://www.fsf.org/licensing/licenses/agpl-3.0.html'
    - source_link = link_to 'Shapado', 'http://gitorious.org/shapado'
    = raw t('.powered_by', :agpl_link => agpl_link, :source_link => source_link, :version => AppConfig.version)
    - if current_group.enable_mathjax
      = link_to('& mathjax', 'http://www.mathjax.org')
      = raw("<script type='text/javascript'>$('[data-layout=question]').removeClass('pjax')</script>")

  .feedback{:style => "display:none"}
    = render :partial => "welcome/feedback"

  = render "shared/layout/javascript"
  = render "shared/layout/websocket"
  - if current_group.shapado_version.has_custom_js?
    - if current_group.current_theme.has_js
      %script{type: 'text/javascript'}
        =raw current_group.current_theme.javascript.read

app/views/shared/layout/_head.html.haml
%title
  &= page_title
= render "shared/layout/css"

= javascript_include_tag "modernizr.js"

= raw(current_group.head_tag)
= render "shared/layout/meta"

-if @feed_urls && !@feed_urls.empty?
  -@feed_urls.each do |title, url|
    %link{:rel=>"alternate", :type=>"application/atom+xml", :title => title, :href=> url}

= render "shared/analytics"

app/views/shared/layout/_header.html.haml
= render "shared/widgets", :context => 'mainlist', :position => 'header'
%header
  -announcements = current_announcements(session[:announcement_hide_time])
  -unless announcements.empty?
    .announcement
      %p
        - announcements.each do |announcement|
          = markdown(announcement.message)
      = link_to t('scaffold.close'), hide_announcements_path, :id => "hide_announcement"

  -if !(params[:controller] =~ /moderate\//)
    - questions_link =  questions_link_for(params[:context])
    = render "shared/content-nav", :questions_link => questions_link

  .title.clearfix
    -cc = yield :header
    -if !cc.blank?
      = cc
    -else
      -if !(params[:controller] =~ /moderate\//)
        = render "shared/quick_question_box"

  %nav
    .filters.clearfix.clearfix{:class => @active_subtab }
      %ul.menubar
        = yield :nav_filters

app/views/shared/layout/_javascript.html.haml
%script{ src: "//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" }

- jq = "#{javascript_include_tag("jquery.js")}".gsub('</script>', '<\/script>')
:javascript
  window.jQuery || document.write('#{jq}')

- if current_group.shapado_version.has_custom_js?
  -current_theme = current_group.current_theme || Theme.where(:is_default => true).first
  %meta{'data-has-js'=> current_theme.has_js, 'data-theme-js' => javascript_group_path(current_group, params[:test_theme] || current_theme.id, current_theme.version)}

= javascript_include_tag "application", :debug => Rails.env.development? && params[:debugjs]
= javascript_include_tag "i18n/#{I18n.locale}"

= yield :js

/[if lt IE 7 ]
  <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
  <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>

app/views/shared/layout/_meta.html.haml
%meta{ :content => "text/html; charset=utf-8", "http-equiv" => "Content-Type" }
%meta{ :geo_local => current_group.track_users }

=yield :head

-if current_group.has_custom_favicon?
  %link{:rel=>"icon", :type=>"image/png", :href=>favicon_group_path(current_group)}
-else
  %link{:rel=>"icon", :type=>"image/png", :href=>"/favicon.ico"}

=render :partial => "shared/layout/feeds"

= csrf_meta_tag

app/views/shared/layout/_notice.html.haml
%h4
  = link_to h(current_group.name), about_path

.markdown
  = auto_link(markdown(current_group.description))

app/views/shared/layout/_websocket.html.haml
#websocket{:"data-key" => logged_in? ? current_user.socket_key : nil, :"data-group" => current_group.id, :"data-host" => request.host}
#chat_div{:"data-title" => "Chat: #{current_group.name}", :"data-user" => logged_in? ? current_user.id : nil}