config/routes.rb
ENV["MAGENT_WEB_PATH"] = "/magent"
require 'magent_web'

#ENV["BUGHUNTER_PATH"] = "/errors"
#require 'bug_hunter'

Rails.application.routes.draw do
  devise_for(:users,
             :path_names => {:sign_in => 'login', :sign_out => 'logout'},
             :controllers => {:registrations => 'users', :omniauth_callbacks => "multiauth/sessions"}) do
  end
  match '/groups/:group_id/check_custom_domain' => 'groups#check_custom_domain',
  :as => 'check_custom_domain'
  match '/groups/:group_id/reset_custom_domain' => 'groups#reset_custom_domain',
   :method => :post, :as => 'reset_custom_domain'
  match '/connect' => 'users#social_connect', :method => :get, :as => :social_connect
  match '/invitations/accept' => 'invitations#accept', :method => :get, :as => :accept_invitation
  match '/disconnect_twitter_group' => 'groups#disconnect_twitter_group', :method => :get
  match '/group_twitter_request_token' => 'groups#group_twitter_request_token', :method => :get
  match 'confirm_age_welcome' => 'welcome#confirm_age', :as => :confirm_age_welcome
  match '/change_language_filter' => 'welcome#change_language_filter', :as => :change_language_filter
  match '/register' => 'users#create', :as => :register
  match '/signup' => 'users#new', :as => :signup
  match '/plans' => 'doc#plans', :as => :plans
  match '/chat' => 'doc#chat', :as => :chat
  match '/shapado_feedback' => 'welcome#feedback', :as => :feedback
  match '/feedback' => 'welcome#fake_feedback'
  match '/send_feedback' => 'welcome#send_shapado_feedback', :as => :send_feedback
  match '/send_shapado_feedback' => 'welcome#send_feedback', :as => :send_feedback
  match '/settings' => 'users#edit', :as => :settings
  match '/tos' => 'doc#tos', :as => :tos
  match '/privacy' => 'doc#privacy', :as => :privacy
  match '/widgets/embedded/:id' => 'widgets#embedded', :as => :embedded_widget
  match '/suggestions' => 'users#suggestions', :as => :suggestions
  match '/activities' => 'activities#index', :as => :activities
  match '/activities/:id' => 'activities#show', :as => :activity, :method => :get

  match '/update_stripe' => 'invoices#webhook', :method => :post

  get "mobile/index"

  match '/users/auth/:provider' => 'users#auth', :as => :auth_users

  match '/facebook' => "facebook#index", :as => :facebook, :method => :any
  match '/facebook/enable_page' => 'facebook#enable_page', :as => :enable_page_facebook

  mount MagentWeb.app => ENV["MAGENT_WEB_PATH"]
#  mount BugHunter.app => ENV["BUGHUNTER_PATH"]

  match '/facts' => redirect("/")
  match '/users/:id/:slug' => redirect("/users/%{slug}"), :as => :user_se_url, :id => /\d+/
  resources :users do
    collection do
      get :autocomplete_for_user_login
      post :connect
      get :follow_tags
      get :unfollow_tags
      get :leave
      get :join
      post :connect
      get :new_password
    end

    member do
      get :feed
      get :expertise
      get :preferred
      get :by_me
      get :contributed
      post :unfollow
      post :follow
      get :answers
      get :follows
      get :activity
    end
  end

  resources :badges

  resources :searches, :path => "search", :as => "search"

  resources :pages do
    member do
      get :js
      get :css
    end
  end

  resources :announcements do
    collection do
      get :hide
    end
  end

  resources :imports do
    collection do
      post :send_confirmation
    end
  end

  get '/questions/:id/:slug' => 'questions#show', :as => :se_url, :id => /\d+/
  post '/questions/:id/start_reward' => "reward#start", :as => :start_reward
  get '/questions/:id/close_reward' => "reward#close", :as => :close_reward

  match '/answers(.format)' => 'answers#index', :as => :answers

  scope('questions') do
    resources :tags, :constraints => { :id => /\S+/ }
  end

  match 'questions/unanswered' => redirect("/questions?unanswered=1")

  resources :questions do
    resources :votes
    resources :flags
    collection do
      get :tags_for_autocomplete
      get :related_questions
      get :random

      match '/:filter' => 'questions#index', :as => :filtered, :constraints => { :filter => /all|unanswered|by_me|feed|preferred|contributed|expertise/ }
    end

    member do
      get :solve
      get :unsolve
      get :flag
      get :follow
      get :unfollow
      get :history
      get :revert
      get :diff
      get :move
      put :move_to
      get :retag
      put :retag_to
      get :remove_attachment
      get :twitter_share
    end

    resources :comments do
      resources :votes
    end

    resources :answers do
      resources :votes
      resources :flags
      member do
        get :favorite
        get :unfavorite
        get :flag
        get :history
        get :diff
        get :revert
      end

      resources :comments do
        resources :votes
      end
    end

    resources :close_requests
    resources :open_requests
  end

  match 'questions/tags/:tags' => 'tags#show', :as => :question_tag
  match 'questions/tagged/:tags' => redirect { |env, req| "/questions/tags/#{req.params[:tags].gsub(' ', '+')}" }, :tags => /.+/ #support se url

  resources :groups do
    collection do
      get :autocomplete_for_group_slug
      get :add_to_facebook
      post :join
    end

    member do
      get :allow_custom_ads
      get :disallow_custom_ads
      post :close
      post :update_card
      get :accept

      post :upgrade
      post :downgrade
      post :set_columns
    end
  end

  resources :invitations do
    member do
      post :revoke
      post :resend
    end
  end

  resources :invoices do
    member do
      get :success
    end
    collection do
      get :auto_update
      get :upcoming
    end
  end

  scope '/manage' do
    resources :widgets do
      member do
        post :move
      end
    end

    resources :themes do
      member do
        get :remove_bg_image
        put :apply
        get :ready
        get :download
      end

      collection do
        post :import
      end
    end
    resources :constrains_configs
    resources :members
  end

  scope '/manage', :as => 'manage' do
    controller 'admin/manage' do
      match 'edit_card' => :edit_card
      match 'social' => :social
      match 'properties' => :properties
      match 'theme' => :theme
      match 'actions' => :actions
      match 'stats' => :stats
      match 'reputation' => :reputation
      match 'content' => :content
      match 'invitations' => :invitations
      match 'appearance' => :appearance
      match 'access' => :access
      match 'close_group' => :close_group
    end
  end
  match '/manage/properties/:tab' => 'admin/manage#properties', :as => :manage_properties_tab

  namespace :moderate do
    resources :questions do
      collection do
        get :flagged
        get :to_close
        get :to_open
        post :manage
      end
      member do
        get :banning
        put :ban

        get :closing
        put :close
        get :opening
        put :open
      end
    end
    resources :answers do
      collection do
        post :manage
      end
      member do
        get :banning
        put :ban
      end
    end
    resources :users
  end

  match '/moderate' => 'moderate/questions#index'
#   match '/search' => 'searches#index', :as => :search
  match '/about' => 'groups#show', :as => :about
  root :to => 'questions#index'
  #match '/:controller(/:action(/:id))'
  match '*a', :to => 'public_errors#routing'
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :login_required, :except => [:show, :create, :index, :history, :diff]
  before_filter :check_permissions, :only => [:destroy, :create]
  before_filter :check_update_permissions, :only => [:edit, :update, :revert]
  before_filter :track_pageview

  helper :votes

  def index
    exclude = [:votes, :_keywords]
    if params[:question_id]
      @question = current_group.questions.by_slug(params[:question_id])
      @answers = @question.answers.without(exclude).page(params["page"])
    else
      @answers = current_group.answers.without(exclude).page(params["page"])
    end

    respond_to do |format|
      format.html
      format.json { render :json => @answers }
    end
  end

  def history
    @answer = current_group.answers.find(params[:id])
    @question = @answer.question

    respond_to do |format|
      format.html
      format.json { render :json => @answer.versions.to_json }
    end
  end

  def diff
    @answer = current_group.answers.find(params[:id])
    @question = @answer.question
    @prev = params[:prev]
    @curr = params[:curr]
    if @prev.blank? || @curr.blank? || @prev == @curr
      flash[:error] = "please, select two versions"
      render :history
    else
      if @prev
        @prev = (@prev == "current" ? :current : @prev.to_i)
      end

      if @curr
        @curr = (@curr == "current" ? :current : @curr.to_i)
      end
    end
  end

  def revert
    @question = @answer.question
    @answer.load_version(params[:version].to_i)

    respond_to do |format|
      format.html
    end
  end

  def show
    @answer = current_group.answers.find!(params[:id])
    @question = @answer.question
    respond_to do |format|
      format.html
      format.mobile
      format.json  { render :json => @answer.to_json }
    end
  end

  def create
    @answer = Answer.new
    @answer.safe_update(%w[body wiki anonymous position], params[:answer])
    @answer.anonymous = params[:answer][:anonymous] if current_group.enable_anonymous
    @question = current_group.questions.by_slug(params[:question_id])

    @answer.question = @question
    @answer.group_id = @question.group_id

    # workaround, seems like mm default values are broken
    @answer.votes_count = 0
    @answer.votes_average = 0
    @answer.flags_count = 0

    @answer.user = current_user
    if !logged_in?
      if recaptcha_valid? && params[:user]
        @user = User.where(:email => params[:user][:email]).first
        if @user.present?
          if !@user.anonymous
            flash[:notice] = I18n.t('answers.create.annon_notice')
            return create_draft!
          else
            @answer.user = @user
          end
        elsif current_group.enable_anonymous
          @user = User.new(:anonymous => true, :login => "Anonymous")
          @user.safe_update(%w[name email website], params[:user])
          @user.login = @user.name if @user.name.present?
          @user.save!
          @answer.user = @user
        end
      elsif !AppConfig.recaptcha["activate"] || !current_group.enable_anonymous
        return create_draft!
      end
    end

    respond_to do |format|
      if (logged_in? || (recaptcha_valid? && @answer.user.valid?)) && @answer.save
        @question.add_contributor(current_user || @answer.user)
        link = question_answer_url(@question, @answer)

        Jobs::Activities.async.on_create_answer(@answer.id).commit!
        Jobs::Answers.async.on_create_answer(@question.id, @answer.id, link).commit!

        @question.answer_added!
        sweep_question(@question) # TODO move to magent
        html = ""
        if params[:facebook]
          html = render_to_string(:partial => "facebook/answer",
                                  :locals => {:answer => @answer, :question => @question})
        else
          html = render_to_string(:partial => "questions/answer",
                                  :locals => {:answer => @answer, :question => @question})
        end
        Magent::WebSocketChannel.push({id: "newanswer", object_id: @answer.id, name: @answer.body, channel_id: current_group.slug,
                                       owner_id: @answer.user.id, owner_name: @answer.user.login,
                                       question_id: @question.id, question_title: @question.title,
                                       html: html})
        flash[:notice] = t(:flash_notice, :scope => "answers.create")
        format.html{redirect_to question_path(@question)}
        format.mobile{
          redirect_to question_path(@question, :format => :mobile)
        }
        format.json { render :json => @answer.to_json(:except => %w[_keywords]) }
        format.js do
          render(:json => {:success => true, :message => flash[:notice],
                           :html => html, :question_id => @question.id}.to_json)
        end
      else
        @answer.errors.add(:captcha, "is invalid") if !logged_in? && !recaptcha_valid?

        errors = @answer.errors
        errors.merge!(@answer.user.errors) if @answer.user && @answer.user.anonymous && !@answer.user.valid?
        puts errors.full_messages

        format.html{
          flash[:error] = errors.full_messages
          redirect_to question_path(@question)
        }
        format.json { render :json => errors, :status => :unprocessable_entity }
        format.js {
          flash.now[:error] = errors.full_messages
          render :json => {:success => false, :message => flash.now[:error] }.to_json
        }
      end
    end
  end

  def edit
    @question = @answer.question
    respond_to do |format|
      format.html
      format.js {render :json => {:success => false, :html => render_to_string(:partial => "answers/edit_form",
                                   :locals => {:question => @question, :answer => @answer}) }.to_json }
    end
  end

  def update
    respond_to do |format|
      @question = @answer.question
      @answer.safe_update(%w[body wiki version_message], params[:answer])
      @answer.updated_by = current_user

      if @answer.valid? && @answer.save
        @question.add_contributor(current_user)

        sweep_answer(@answer)

        Question.update_last_target(@question.id, @answer)

        flash[:notice] = t(:flash_notice, :scope => "answers.update")

        Jobs::Activities.async.on_update_answer(@answer.id).commit!

        Magent::WebSocketChannel.push({id: "updateanswer", object_id: @answer.id, name: @answer.body, channel_id: current_group.slug,
                                       owner_id: @answer.user.id, owner_name: @answer.user.login,
                                       question_id: @question.id, question_title: @question.title,
                                       html: render_to_string(:partial => "questions/answer",
                                                              :locals => {:answer => @answer, :question => @question})})

        format.html { redirect_to(question_path(@answer.question, :anchor => "answer#{@answer.id}")) }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @answer.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @question = @answer.question
    if @answer.user_id == current_user.id
      @answer.user.update_reputation(:delete_answer, current_group)
    end
    Jobs::Activities.async.on_destroy_answer(current_user.id, @answer.attributes).commit!
    sweep_answer(@answer)
    @answer.destroy
    @question.answer_removed!
    sweep_question(@question)

    respond_to do |format|
      format.html { redirect_to(question_path(@question)) }
      format.json { head :ok }
    end
  end

  def favorite
    @answer = Answer.find(params[:id])
    @answer.add_favorite!(current_user)
    link = question_answer_url(@answer.question, @answer)
    Jobs::Mailer.async.on_favorite_answer(@answer.id, current_user.id).commit!
    Jobs::Answers.async.on_favorite_answer(@answer.id, current_user.id, link).commit!

    respond_to do |format|
      flash[:notice] = t("favorites.create.success")
      format.html { redirect_to(question_path(@answer.question)) }
      format.mobile { redirect_to(question_path(@answer.question, :format => :mobile)) }
      format.json { head :ok }
      format.js {
        render(:json => {:success => true,
                 :message => flash[:notice], :increment => 1 }.to_json)
      }
    end
  end

  def unfavorite
    @answer = Answer.find(params[:id])
    @answer.remove_favorite!(current_user)

    flash[:notice] = t("unfavorites.create.success")
    respond_to do |format|
      format.html { redirect_to(question_path(@answer.question)) }
      format.mobile { redirect_to(question_path(@answer.question, :format => :mobile)) }
      format.js {
        render(:json => {:success => true,
                 :message => flash[:notice], :increment => -1 }.to_json)
      }
      format.json  { head :ok }
    end
  end

  protected
  def check_permissions
    if params[:id]
      @answer = current_group.answers.find(params[:id])
      if !@answer.nil?
        unless (current_user.can_modify?(@answer) || current_user.mod_of?(@answer.group))
          flash[:error] = t("global.permission_denied")
          redirect_to question_path(@answer.question)
        end
      else
        redirect_to questions_path
      end
    else
      if logged_in? && !current_user.can_answer_on?(current_group)
        reputation = current_group.reputation_constrains["answer"]

        flash[:error] = I18n.t("users.messages.errors.reputation_needed",
                              :min_reputation => reputation,
                              :action => I18n.t("users.actions.answer"))

        respond_to do |format|
          format.html {redirect_to questions_path}
          format.js {
            render(:json => {:success => false,
                           :message => flash[:error] }.to_json)
          }
        end
      end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.haml
-title = answer.question.title

%article.clearfix{:class => "answer #{answer.id}"}
  %h2
    = link_to truncate(strip_tags(answer.body), :length => 200), question_path(answer.question, :anchor => "answer#{answer.id}"), :title => title
  %p
    = link_to answer.question.title, question_path(answer.question), :title => answer.question.body

  =format_number(answer.votes_average)
  =t(:votes, :scope => "activerecord.attributes.question")

app/views/answers/_changes.html.haml
.markdown
  = shapado_auto_link(markdown(version.data["body"]))
.messages
  = version.message

app/views/answers/_diff_actions.html.haml
=link_to t("global.current"), diff_question_answer_path(post.question, post, :curr => number, :prev => "current"), :class => "diff_current"
-if (number-1) >= 0
  |
  =link_to t("global.previous"), diff_question_answer_path(post.question, post, :curr => number, :prev => number-1 ), :class => "diff_prev"
-if logged_in? && ((post.wiki && current_user.can_edit_wiki_post_on?(post.group)) || current_user.can_edit_others_posts_on?(post.group) || current_user.can_modify?(post))
  |
  =link_to t("wiki.actions.revert"), revert_question_answer_path(post.question, post, :version => number)

app/views/answers/_edit_form.html.haml
= form_for(:answer, :url => question_answer_path(question, answer), :html => {:method => :put, :class => "form edit_answer"}) do |f|
  = render :partial => "answers/form", :locals => {:f => f, :markdown => true,:question => question}

app/views/answers/_editor.html.haml
-opts = {:class => "text_area", :rows => '15', :cols => '92'}
-if local_assigns[:markdown]
  -if current_group.wysiwyg_editor
    -opts[:class] = "wysiwyg_editor"
    -opts[:value] = markdown(@answer.body)
  -else
    -opts[:class] = "markdown_editor"

.field.editor
  .markdown
    = f.text_area :body, opts
  -if !current_group.wysiwyg_editor
    .markdown_preview

-if local_assigns[:markdown] && !current_group.wysiwyg_editor
  =markdown(@answer.body)

app/views/answers/_form.html.haml
-if !@question.closed || !(logged_in? && current_user.can_answer_on?(current_group))
  =form_for [@question, @answer ||= Answer.new], :html => {:class => "add_answer markdown"} do |f|
    = render 'shared/editor', :f => f, markdown: true
    -if @answer.position
      = hidden_field_tag "answer[position][lat]", @answer.position["lat"], :class => "lat_input"
      = hidden_field_tag "answer[position][long]", @answer.position["long"], :class => "long_input"
    -if !@answer.new?
      .field
        = f.label :version_message, t("wiki.model.attributes.message"), :class => "label"
        = f.text_field :version_message, :class => "text_field"
    -elsif !logged_in?
      = render :partial => "users/anonymous_form"

    .field.form-options
      .column
        .checkbox
          = f.label :wiki, "Wiki"
          = f.check_box :wiki, :class => "checkbox"
      - if logged_in? && current_group.enable_anonymous
        .column
          .checkbox
            = f.label :anonymous, t("scaffold.post_as_anonymous"), :class => "radio"
            = f.check_box :anonymous, {:class => "checkbox"}, true, false

      -if AppConfig.mailing && AppConfig.mailing["activate"]
        .column.by_mail
          %a{:href => "mailto:#{@question.email}"}
            = I18n.t('questions.toolbar.answer_by_mail')

      .buttons
        = submit_tag t('answers.form.submit'), :class => "save"

app/views/answers/diff.html.haml
-content_for :subtabs do
  .navtitle
    =t("wiki.diff.title", :prev => @prev, :curr => @curr)

=render :partial => "wiki/diff", :locals => {:post => @answer, :prev => @prev, :curr => @curr, :scope => "activerecord.attributes.answer", :versioned_keys => [:body] }

%br
.form
  .group.navform
    = link_to(t("wiki.actions.all_history"), history_question_answer_path(@question, @answer))
    = t("global.or")
    = link_to(t("wiki.actions.back_to_question"), question_path(@question))

app/views/answers/edit.html.haml
-content_for :subtabs do
  .navtitle
    = t(".title")

= render "edit_form", :question => @question, :answer => @answer

app/views/answers/flag.html.haml
%h2
  Flag answer

= render :partial => "flags/form", :locals => {:flag => @flag, :source => question_path(@answer.question)}

app/views/answers/history.html.haml
-counter = @answer.versions.count

= form_tag diff_question_answer_path(@question, @answer), :method => "GET", :class => "history" do
  %ul
    %li
      .top
        %p.version.current
          =t("wiki.history.current_version")
          .diff
            = radio_button_tag("prev", :current, :checked => @prev == "current")
            = radio_button_tag("curr", :current, :checked => @curr == "current")

          %small
            =link_to t('.back'), question_answer_path(@answer.question, @answer)


      %p.description
        = shapado_auto_link(markdown(@answer.body))
      %p.messages
        = @answer.version_message
      %p.author
        = render "users/user_data", :user => @answer.updated_by || @answer.user

      .version-nav
        -if @answer.versions.count > 0
          =link_to t("global.previous"), diff_question_path(@answer, :curr => :current, :prev => @answer.versions.count-1 )
        -if !@answer.version_message.blank?
          = t('wiki.history.version_summary')


    -@answer.versions.reverse_each do |version|
      -counter -= 1
      -if !version.data.empty?
        = render :partial => "wiki/version", :object => version, :locals => {:post => @answer, :number => counter, :prev => @prev, :curr => @curr, :scope => "activerecord.attributes.question"}

  .buttons-history
    = submit_tag t("wiki.actions.show_diff"), :value => "diff", :name => "show"
    = t("global.or")
    = link_to(t("scaffold.back"), question_answer_path(@answer.question, @answer))

app/views/answers/index.html.haml
-@answers.each do |answer|
  -@question = answer.question
  -next if @question.nil?
  =render 'answers/answer', :answer => answer, :question => @question


= paginate @answers

app/views/answers/revert.html.haml
-content_for :subtabs do
  .navtitle
    = t(".title")

= form_for(:answer, :url => question_answer_path(@question, @answer), :html => {:method => :put, :class => "form"}) do |f|
  =render :partial => "form", :locals => {:f => f, :markdown => true}
  .field-group
    .buttons
      = f.submit t("scaffold.update")
      = t("global.or")
      = link_to t("scaffold.cancel"), history_question_answer_path(@question, @answer), :class => "button cancel"

app/views/answers/show.html.haml
= include_latex
- question_body = find_and_preserve(shapado_auto_link(markdown(@question.body.present? ? @question.body : @question.title)))

%section#question{:class => "main-question #{@question.id}", :item_scope => '', :itemtype => "http://schema.org/Article"}
  .author
    %p
      %span
        = I18n.t('global.by_semi')
      = render :partial => "users/user_mini", :locals => {:user => @question.user, :author => true}
      %span
        = t('activerecord.attributes.question.created_at')
      %time{:datetime => @question.created_at.iso8601, :itemprop => "datePublished"}
        = t("time.ago", :time => time_ago_in_words(@question.created_at))
      -if !@question.user.hide_country && @question.address.present?
        %span
          = t("global.from", :site => CGI.escape_html(@question.address_name))
    %h1{:itemprop => "name"}
      = link_to @question.title, question_path(@question)
      - if @question.closed
        =" [#{t("closed", :scope => "activerecord.attributes.question").upcase}]"

    .description.markdown
      .clearfix{:itemprop => "articleBody"}
        = question_body

#answers-content-wrap
  .answers-list
    = render :partial=> "questions/answer", :locals=> {:question => @question, :answer => @answer, :comment => Answer.new}

app/views/answers/show.mobile.haml
- qpath = question_path(@question, :format => :mobile)
- apath = question_answer_path(@question, @answer, :format => :mobile)

- if params[:actions]
  %div{:data => {:role => "page"}}
    %div{:"data-role"=>"header", :"data-theme"=>"d", :"data-position"=>"inline"}
      %h1
        = t('global.actions')

    %div{:"data-role" => "content", :"data-theme" => "c"}
      %p
        = t('global.what_to_do')
      = link_to t('global.view'), apath, :"data-role" => "button", :"data-theme" => "e"
      - if logged_in?
        - if current_user.can_modify?(@question)
          = link_to t('scaffold.edit'), edit_question_answer_path(@question, @answer, :format => :mobile), :"data-role" => "button", :"data-theme" => "c"

        = link_to t('users.action.vote_up'), question_answer_votes_path(@question, @answer, :vote_up => true, :source => qpath), :method => :post, :"data-role" => "button", :"data-theme" => "c"
        = link_to t('users.actions.vote_down'), question_answer_votes_path(@question, @answer, :vote_down => true, :source => qpath), :method => :post, :"data-role" => "button", :"data-theme" => "c"
        - if logged_in? && @answer.favorite_for?(current_user)
          = link_to t(".unfavorite"), unfavorite_question_answer_path(@question, :format => :mobile), :"data-role" => "button", :"data-theme" => "c"
        -else
          = link_to t(".favorite"), favorite_question_answer_path(@question, :format => :mobile), :"data-role" => "button", :"data-theme" => "c"
      = link_to t('global.view_question'), qpath, :"data-role" => "button", :"data-theme" => "b"
-else
  = include_latex
  - question_body = find_and_preserve(shapado_auto_link(markdown(@question.body.present? ? @question.body : @question.title)))

  %div{:data => {:role => "page"}}
    %div{:"data-role" => "header"}
      %h1
        = @question.title[0,20]+"..."

      = render "shared/mobile/header_actions"

    %div{:"data-role" => "content"}
      %h1
        = link_to h(@question.title), qpath, :"data-role" => "none"

      %div{:"data-role" => "content"}
        .markdown
          = question_body

      %h2
        = t('activerecord.models.answer')

      %div{:"data-role" => "content"}
        .markdown
          =find_and_preserve(shapado_auto_link(markdown(@answer.body), :link_users => true))