config/routes.rb
ENV["MAGENT_WEB_PATH"] = "/magent"
require 'magent_web'

#ENV["BUGHUNTER_PATH"] = "/errors"
#require 'bug_hunter'

Rails.application.routes.draw do
  devise_for(:users,
             :path_names => {:sign_in => 'login', :sign_out => 'logout'},
             :controllers => {:registrations => 'users', :omniauth_callbacks => "multiauth/sessions"}) do
  end
  match '/groups/:group_id/check_custom_domain' => 'groups#check_custom_domain',
  :as => 'check_custom_domain'
  match '/groups/:group_id/reset_custom_domain' => 'groups#reset_custom_domain',
   :method => :post, :as => 'reset_custom_domain'
  match '/connect' => 'users#social_connect', :method => :get, :as => :social_connect
  match '/invitations/accept' => 'invitations#accept', :method => :get, :as => :accept_invitation
  match '/disconnect_twitter_group' => 'groups#disconnect_twitter_group', :method => :get
  match '/group_twitter_request_token' => 'groups#group_twitter_request_token', :method => :get
  match 'confirm_age_welcome' => 'welcome#confirm_age', :as => :confirm_age_welcome
  match '/change_language_filter' => 'welcome#change_language_filter', :as => :change_language_filter
  match '/register' => 'users#create', :as => :register
  match '/signup' => 'users#new', :as => :signup
  match '/plans' => 'doc#plans', :as => :plans
  match '/chat' => 'doc#chat', :as => :chat
  match '/shapado_feedback' => 'welcome#feedback', :as => :feedback
  match '/feedback' => 'welcome#fake_feedback'
  match '/send_feedback' => 'welcome#send_shapado_feedback', :as => :send_feedback
  match '/send_shapado_feedback' => 'welcome#send_feedback', :as => :send_feedback
  match '/settings' => 'users#edit', :as => :settings
  match '/tos' => 'doc#tos', :as => :tos
  match '/privacy' => 'doc#privacy', :as => :privacy
  match '/widgets/embedded/:id' => 'widgets#embedded', :as => :embedded_widget
  match '/suggestions' => 'users#suggestions', :as => :suggestions
  match '/activities' => 'activities#index', :as => :activities
  match '/activities/:id' => 'activities#show', :as => :activity, :method => :get

  match '/update_stripe' => 'invoices#webhook', :method => :post

  get "mobile/index"

  match '/users/auth/:provider' => 'users#auth', :as => :auth_users

  match '/facebook' => "facebook#index", :as => :facebook, :method => :any
  match '/facebook/enable_page' => 'facebook#enable_page', :as => :enable_page_facebook

  mount MagentWeb.app => ENV["MAGENT_WEB_PATH"]
#  mount BugHunter.app => ENV["BUGHUNTER_PATH"]

  match '/facts' => redirect("/")
  match '/users/:id/:slug' => redirect("/users/%{slug}"), :as => :user_se_url, :id => /\d+/
  resources :users do
    collection do
      get :autocomplete_for_user_login
      post :connect
      get :follow_tags
      get :unfollow_tags
      get :leave
      get :join
      post :connect
      get :new_password
    end

    member do
      get :feed
      get :expertise
      get :preferred
      get :by_me
      get :contributed
      post :unfollow
      post :follow
      get :answers
      get :follows
      get :activity
    end
  end

  resources :badges

  resources :searches, :path => "search", :as => "search"

  resources :pages do
    member do
      get :js
      get :css
    end
  end

  resources :announcements do
    collection do
      get :hide
    end
  end

  resources :imports do
    collection do
      post :send_confirmation
    end
  end

  get '/questions/:id/:slug' => 'questions#show', :as => :se_url, :id => /\d+/
  post '/questions/:id/start_reward' => "reward#start", :as => :start_reward
  get '/questions/:id/close_reward' => "reward#close", :as => :close_reward

  match '/answers(.format)' => 'answers#index', :as => :answers

  scope('questions') do
    resources :tags, :constraints => { :id => /\S+/ }
  end

  match 'questions/unanswered' => redirect("/questions?unanswered=1")

  resources :questions do
    resources :votes
    resources :flags
    collection do
      get :tags_for_autocomplete
      get :related_questions
      get :random

      match '/:filter' => 'questions#index', :as => :filtered, :constraints => { :filter => /all|unanswered|by_me|feed|preferred|contributed|expertise/ }
    end

    member do
      get :solve
      get :unsolve
      get :flag
      get :follow
      get :unfollow
      get :history
      get :revert
      get :diff
      get :move
      put :move_to
      get :retag
      put :retag_to
      get :remove_attachment
      get :twitter_share
    end

    resources :comments do
      resources :votes
    end

    resources :answers do
      resources :votes
      resources :flags
      member do
        get :favorite
        get :unfavorite
        get :flag
        get :history
        get :diff
        get :revert
      end

      resources :comments do
        resources :votes
      end
    end

    resources :close_requests
    resources :open_requests
  end

  match 'questions/tags/:tags' => 'tags#show', :as => :question_tag
  match 'questions/tagged/:tags' => redirect { |env, req| "/questions/tags/#{req.params[:tags].gsub(' ', '+')}" }, :tags => /.+/ #support se url

  resources :groups do
    collection do
      get :autocomplete_for_group_slug
      get :add_to_facebook
      post :join
    end

    member do
      get :allow_custom_ads
      get :disallow_custom_ads
      post :close
      post :update_card
      get :accept

      post :upgrade
      post :downgrade
      post :set_columns
    end
  end

  resources :invitations do
    member do
      post :revoke
      post :resend
    end
  end

  resources :invoices do
    member do
      get :success
    end
    collection do
      get :auto_update
      get :upcoming
    end
  end

  scope '/manage' do
    resources :widgets do
      member do
        post :move
      end
    end

    resources :themes do
      member do
        get :remove_bg_image
        put :apply
        get :ready
        get :download
      end

      collection do
        post :import
      end
    end
    resources :constrains_configs
    resources :members
  end

  scope '/manage', :as => 'manage' do
    controller 'admin/manage' do
      match 'edit_card' => :edit_card
      match 'social' => :social
      match 'properties' => :properties
      match 'theme' => :theme
      match 'actions' => :actions
      match 'stats' => :stats
      match 'reputation' => :reputation
      match 'content' => :content
      match 'invitations' => :invitations
      match 'appearance' => :appearance
      match 'access' => :access
      match 'close_group' => :close_group
    end
  end
  match '/manage/properties/:tab' => 'admin/manage#properties', :as => :manage_properties_tab

  namespace :moderate do
    resources :questions do
      collection do
        get :flagged
        get :to_close
        get :to_open
        post :manage
      end
      member do
        get :banning
        put :ban

        get :closing
        put :close
        get :opening
        put :open
      end
    end
    resources :answers do
      collection do
        post :manage
      end
      member do
        get :banning
        put :ban
      end
    end
    resources :users
  end

  match '/moderate' => 'moderate/questions#index'
#   match '/search' => 'searches#index', :as => :search
  match '/about' => 'groups#show', :as => :about
  root :to => 'questions#index'
  #match '/:controller(/:action(/:id))'
  match '*a', :to => 'public_errors#routing'
end

app/models/tag.rb
class Tag
  include Mongoid::Document
  include Mongoid::Timestamps
  include MongoidExt::Storage

  identity :type => String
  paginates_per 100

  field :name,  :type => String
  field :description, :type => String
  field :count, :type => Integer, :default => 0
  field :langs, :type => Array
  field :color, :type => String
  field :used_at, :type => Time, :default => Time.now
  field :followers_count, :type => Integer, :default => 0

  file_key :icon, :max_length => 256.kilobytes

  referenced_in :group
  referenced_in :user

  index :name
  index :group_id

  validates_uniqueness_of :name, :scope => :group_id, :allow_blank => false

  validates_length_of       :name,     :minimum => 1

  def self.find_file_from_params(params, request)
    if request.path =~ %r{/(icon)/([^/\.\?]+)/([^\/\.\?]+)}
      @group = Group.find($2)
      @tag = @group.tags.where(:name => $3).first
      case $1
      when "icon"
        @tag.icon
      end
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :login_required, :except => [:index, :show]
  before_filter :moderator_required, :except => [:index, :show]
  before_filter :track_pageview

  def index
    @tags = current_scope.page(params["page"])

    respond_to do |format|
      format.html do
        set_page_title(t("layouts.application.tags"))
      end
      format.js do
        html = render_to_string(:partial => "tag_table", :locals => {:tag_table => @tags})
        render :json => {:html => html}
      end
      format.json  { render :json => @tags.to_json }
    end
  end

  def show
    @current_tags = @tag_names = params[:id].split("+")
    @tags =  current_scope.where(:name.in => @tag_names)
    @questions = current_group.questions.where(:tags => {:$all => @tag_names}, :banned => false).page(params["page"])
    @title = I18n.t('tags.show.title', :tags => @tag_names.join(', '))
    #add_feeds_url(url_for(:format => "atom"), t("feeds.question"))

    set_page_title(@title)

    respond_to do |format|
      format.html
      format.atom do
        render '/questions/index', :format => 'atom'
      end
      format.json do
        html = render_to_string(:partial => "tags/show_json",
                                  :locals => {:tag => @tags.first})
        render :json => { :html => html }
      end
    end
  end

  def new
    @tag = Tag.new
  end

  def edit
    @tag = current_scope.where(:$or => [{:name => params[:id]}, {:_id => params[:id]}]).first
  end

  def create
    @tag = Tag.new
    @tag.safe_update(%w[name icon description], params[:tag])

    @tag.group = current_group
    @tag.user = current_user

    if @tag.save
      redirect_to tag_url(@tag)
    else
      render :action => :new
    end
  end

  def update
    @tag = current_scope.find(params[:id])
    @tag.safe_update(%w[name icon description], params[:tag])
    @name_changes = @tag.changes["name"]

    saved = @tag.save
    merge = (params[:merge] == "1" && !@tag.errors[:name].blank?)

    if saved || merge
      if @name_changes
        if merge
          Question.pull({group_id: @tag.group_id, :tags => {:$all => [@name_changes.first, @name_changes.last]}},
                        "tags" => @name_changes.first)
        end
        Question.override({group_id: @tag.group_id, :tags => @name_changes.first}, {"tags.$" => @name_changes.last})
      end
      redirect_to tag_url(:id => @tag.name)
    else
      render :action => "edit"
    end
  end

  def destroy
    @tag = current_scope.find(params[:id])
    tag_name = @tag.name
    @tag.destroy
    Question.pull({group_id: @tag.group_id, :tags => {:$in => [tag_name]}}, "tags" => tag_name)
    redirect_to tags_url
  end

  protected
  def current_scope
    if(!params[:q].blank?)
      current_group.tags.where(:name => /^#{Regexp.escape(params[:q])}/)
    else
      current_group.tags
    end
  end

end

app/views/tags/_form.html.haml
= form_for(@tag, :html => {:class => "form", :multipart => true}) do |form|
  = error_messages_for(:tag)
  .field
    = form.label :name
    = form.text_field :name, :class => "textfield"

  .field
    = form.label :icon
    = form.file_field :icon

  .field
    = form.label :description
    = form.text_area :description, :class => "textarea"

  -if !(@tag.new_record? || @tag.errors[:name].blank?)
    == The tag '#{@name_changes.last}' already exists
    .field
      = check_box_tag "merge"
      == "MERGE"

  .buttons
    =form.submit nil, :class => "save"

app/views/tags/_show_json.haml
.tooltip
  - if tag && tag.has_icon?
    .tooltip-avatar
      = image_tag(tag_icon_path(current_group,tag.name))

  .tooltip-name
    %p= t('questions.index.has_followers', :count => tag.followers_count.to_i)
    = follow_tag_link(tag)
  .tooltip-description
    - if !tag.description.blank?
      = tag.description
    - else
      - if logged_in? && current_user.mod_of?(current_group)
        = link_to t('tags.show_json.edit_it'), edit_tag_path(tag)
      - else
        = t('tags.show_json.no_description')

app/views/tags/_tag.html.haml
%h2
  = tag.name
  -if local_assigns[:show_counter]
    (#{tag.count})
.tools
  -if logged_in? && current_user.mod_of?(current_group)
    = link_to t("scaffold.edit"), edit_tag_path(tag)
    = link_to t("scaffold.destroy"), tag_path(tag), :method => :delete, :sure => t("scaffold.sure", :model => "tag")
  = follow_tag_link(tag)

app/views/tags/_tag_table.html.haml
%table.tag-list{:style => "width: 100%"}
  = tag_table.each_slice(4) do |tags|
    %tr
      - tags.each do |tag|
        %td{:style => "line-height: 14px"}
          %span.tag{:class => "tag_#{tag}"}
            = tag_link(tag)
            %span.count
              = tag.count.to_i
#additional_info
  = paginate @tags

app/views/tags/edit.html.haml
%h1 Editing tag: "Aqui nombre del tag"
= render "form"

app/views/tags/index.html.haml
.top
  %h1
    = t('activerecord.models.tags')
  .filter
    = form_tag "/questions/tags", :class => "form", :id => "filter_tags", :method => "get" do
      .field
        = text_field_tag "q", params[:q], :class => "text_field filter_field", placeholder: t(".filter")
        = submit_tag("filter")

  -if logged_in? && current_user.mod_of?(current_group)
    = link_to t("scaffold.new", :model =>"tag"), new_tag_url

#tag_table
  = render(:partial => "tag_table", :locals => {:tag_table => @tags})

app/views/tags/new.html.haml
-content_for :subtabs do
  .navtitle
    = t(".title")

= render "form"

app/views/tags/show.html.haml
-feed_url = url_for(:format => "atom", :tags => @tag_names.join("+"))

-content_for :rss do
  %link{:rel=>"alternate", :type=>"application/atom+xml", :title => "atom", :href=> feed_url}

.tags-list

  %h1
    = t('layouts.application.tags')
  .tags
    -@tags.each do |tag|
      .each
        = render "tag", :tag => tag, :show_counter => true
        -if tag.has_icon?
          = image_tag tag_icon_path(current_group,tag.name)
        %p
          = tag.description

  %section
    -if @questions.empty?
      %article.question
        %li.highlight
        = t(".empty")
    -@questions.each do |question|
      = render "questions/question", :question => question

  = paginate @questions